services:
  # Application

  prisma-choa-db:
    container_name: micro_choa_db
    image: "postgres:alpine"
    restart: always
    ports:
      - "45432:5432"
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=f2966052964454b6601c83f1cc08ab97
      - POSTGRES_DB=prisma-choa-db
    volumes:
      - "postgresql_choa:/var/lib/postgresql/choa"

    networks:
      - app-net

  redis-choa-db:
      container_name: redis_choa_db
      image: "redis:6-alpine"
      command: redis-server --requirepass f2966052964454b6601c83f1cc08ab97
      restart: always
      ports:
        - "46378:6379"
      environment:
        - IP=0.0.0.0
        - REDIS_USER=admin
        - REDIS_PASSWORD=f2966052964454b6601c83f1cc08ab97
      #volumes:
      #  - "cache_data:/data"

      networks:
        - app-net

  mongodb:
    container_name: micro_mongo_db
    image: prismagraphql/mongo-single-replica:4.4.3-bionic
    restart: always

    environment:
      MONGO_INITDB_ROOT_USERNAME: adminmongodb
      MONGO_INITDB_ROOT_PASSWORD: f2966052964454b6601c83f1cc08ab97

    ports:
      - 27017:27017

    volumes:
      - mongo:/var/lib/mongo

    networks:
      - app-net

networks:
  app-net:
    driver: bridge

volumes:
  postgresql_choa:
    driver: local

  redis_choa_db:
    driver: local

  mongo:
    driver: local
