
services:
  # Application

  sessiondb:
    container_name: micro_session_db
    image: "postgres:alpine"
    restart: always
    ports:
      - "35432:5432"
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=
      - POSTGRES_DB=sessiondb
    volumes:
      - "postgresql_session:/var/lib/postgresql/session"

    networks:
      - app-net

  prisma-choa-db:
    container_name: micro_choa_db
    image: "postgres:alpine"
    restart: always
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=
      - POSTGRES_DB=
    volumes:
      - "postgresql_choa:/var/lib/postgresql/choa"

    networks:
      - app-net

  admindb:
    container_name: micro_admin_db
    image: "postgres:alpine"
    restart: always
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=
      - POSTGRES_DB=
    volumes:
      - "postgresql_admin:/var/lib/postgresql/admin"

    networks:
      - app-net

  mongodb:
    container_name: micro_mongo_db
    image: prismagraphql/mongo-single-replica:4.4.3-bionic
    restart: always

    environment:
      MONGO_INITDB_ROOT_USERNAME: adminmongodb
      MONGO_INITDB_ROOT_PASSWORD:

    ports:
      - 27017:27017

    volumes:
      - mongo:/var/lib/mongo

    networks:
      - app-net

networks:
  app-net:
    driver: bridge

volumes:
  postgresql_choa:
    driver: local

  postgresql_session:
    driver: local

  postgresql_admin:   # Adicionado o volume faltante
    driver: local

  mongo:
    driver: local
